# Combining extant data and extinct data for PyRate and DES

## Loading packages

In [1]:
library("SpeciesAge")
library("ape")

Le chargement a nécessité le package : ape

Le chargement a nécessité le package : diversitree

Le chargement a nécessité le package : TreeSim

Le chargement a nécessité le package : geiger

Le chargement a nécessité le package : phytools

Le chargement a nécessité le package : maps

Le chargement a nécessité le package : picante

Le chargement a nécessité le package : vegan

Le chargement a nécessité le package : permute

Le chargement a nécessité le package : lattice

This is vegan 2.6-8


Attachement du package : ‘vegan’


L'objet suivant est masqué depuis ‘package:phytools’:

    scores


Le chargement a nécessité le package : nlme

## Loading data

In [2]:
tree_list <- read.tree("../Data_orectolobiformes/posterior_distribution_100_tree_orecto.tree")

In [3]:
tabl <- read.table("Data/Data_Occ_sp_Orecto_TaxonList.txt", sep ="\t", header = TRUE)

In [4]:
lst_files_TS_TE <- list.files("PyRate/Species_combined/TS_TE/", full.names = TRUE)

In [ ]:
lst_files_DES <- list.files("../DES/Analysis_ML/sp_1/", full.names = TRUE)

In [5]:
tab <- read.csv("PyRate/Rates_sp.csv", header = FALSE, sep =";")

## Combining data

In [6]:
tr_nb_list<-sample(100, 20, replace = FALSE)

for (i in 1:20){
    tr <- tree_list[[tr_nb_list[i]]]
    temp <- read.table(lst_files_TS_TE[[i]], sep ="\t", header = TRUE)
    temp_tabl <- cbind(tabl, temp)
    temp_phy <- as.data.frame(cbind(SpeciesAge::calculateTipAges(tr)[,1],lapply(SpeciesAge::calculateTipAges(tr)[,2], meanAge, lambda = mean(unlist(tab[7,-1])), mu = mean(unlist(tab[8,-1])), rho = 38/44)))
    temp_phy2 <- temp_phy[! temp_phy[,1] %in% temp_tabl[,1],2]
    temp_neonto <- as.data.frame(cbind(rep(0,length(temp_phy2)), ((nrow(temp_tabl)+1):(nrow(temp_tabl)+length(temp_phy2))), temp_phy2, rep(0,length(temp_phy2))))
    colnames(temp_neonto) <- colnames(temp)
    data_TS_TE <- rbind(temp, temp_neonto)
    data_TS_TE$clade <- unlist(data_TS_TE$clade)
    data_TS_TE$species <- unlist(data_TS_TE$species)
    data_TS_TE$ts <- unlist(data_TS_TE$ts)
    data_TS_TE$te <- unlist(data_TS_TE$te)
    # write.table(data_TS_TE, paste("PyRate/Test/Occ_sp_Orecto_combined", i, "_G_KEEP_BDS_se_est.txt", sep =""), sep = "\t", col.names = TRUE, row.names = FALSE, quote = FALSE)
    
    
    
}

In [41]:
temp_tab <- temp_tab[-1, ]

In [42]:
temp_tab

    scientificName                       184.5 183.5 182.5 181.5 180.5 179.5
3   Adnetoscyllium angloparisensis       NaN   NaN   NaN   NaN   NaN   NaN
4   Almascyllium cheikheliasi            NaN   NaN   NaN   NaN   NaN   NaN
5   Annea altucuspis                     NaN   NaN   NaN   NaN   NaN   NaN
6   Annea carinata                       NaN   NaN   NaN   NaN   NaN   NaN
7   Annea maubeugei                      NaN   NaN     2     0     0     2
8   Annea myriacuspis                    NaN   NaN   NaN   NaN   NaN   NaN
9   Brachaelurid (gen. nov.) roklumensis NaN   NaN   NaN   NaN   NaN   NaN
10  Cantioscyllium alhaulfi              NaN   NaN   NaN   NaN   NaN   NaN
11  Cantioscyllium bighornensis          NaN   NaN   NaN   NaN   NaN   NaN
12  Cantioscyllium brachyplicatum        NaN   NaN   NaN   NaN   NaN   NaN
13  Cantioscyllium clementsi             NaN   NaN   NaN   NaN   NaN   NaN
14  Cantioscyllium decipiens             NaN   NaN   NaN   NaN   NaN   NaN
15  Cantioscyllium estesi                NaN   NaN   NaN   NaN   NaN   NaN
16  Cantioscyllium hashimiaensis         NaN   NaN   NaN   NaN   NaN   NaN
17  Cantioscyllium lobatum               NaN   NaN   NaN   NaN   NaN   NaN
18  Cantioscyllium markaguntensis        NaN   NaN   NaN   NaN   NaN   NaN
19  Cantioscyllium meyeri                NaN   NaN   NaN   NaN   NaN   NaN
20  Cantioscyllium nessovi               NaN   NaN   NaN   NaN   NaN   NaN
21  Cederstroemia havreensis             NaN   NaN   NaN   NaN   NaN   NaN
22  Cederstroemia nilsi                  NaN   NaN   NaN   NaN   NaN   NaN
23  Cederstroemia siverssoni             NaN   NaN   NaN   NaN   NaN   NaN
24  Cederstroemia triangulata            NaN   NaN   NaN   NaN   NaN   NaN
25  Cederstroemia ziaensis               NaN   NaN   NaN   NaN   NaN   NaN
26  Chiloscyllium broennimanni           NaN   NaN   NaN   NaN   NaN   NaN
27  Chiloscyllium frequens               NaN   NaN   NaN   NaN   NaN   NaN
28  Chiloscyllium gaemersi               NaN   NaN   NaN   NaN   NaN   NaN
29  Chiloscyllium grandis                NaN   NaN   NaN   NaN   NaN   NaN
30  Chiloscyllium greeni                 NaN   NaN   NaN   NaN   NaN   NaN
31  Chiloscyllium humboldti              NaN   NaN   NaN   NaN   NaN   NaN
32  Chiloscyllium meraense               NaN   NaN   NaN   NaN   NaN   NaN
⋮   ⋮                                    ⋮     ⋮     ⋮     ⋮     ⋮     ⋮
97  Palaeorhincodon daouii               NaN   NaN   NaN   NaN   NaN   NaN
98  Palaeorhincodon dartevellei          NaN   NaN   NaN   NaN   NaN   NaN
99  Palaeorhincodon wardi                NaN   NaN   NaN   NaN   NaN   NaN
100 Paraginglymostoma bloti              NaN   NaN   NaN   NaN   NaN   NaN
101 Parahemiscyllium underwoodwardi      NaN   NaN   NaN   NaN   NaN   NaN
102 Pararhincodon crochardi              NaN   NaN   NaN   NaN   NaN   NaN
103 Pararhincodon germaini               NaN   NaN   NaN   NaN   NaN   NaN
104 Pararhincodon groessensi             NaN   NaN   NaN   NaN   NaN   NaN
105 Pararhincodon lehmani                NaN   NaN   NaN   NaN   NaN   NaN
106 Pararhincodon ornatus                NaN   NaN   NaN   NaN   NaN   NaN
107 Pararhincodon ypresiensis            NaN   NaN   NaN   NaN   NaN   NaN
108 Phorcynis catulina                   NaN   NaN   NaN   NaN   NaN   NaN
109 Plicatoscyllium antiquum             NaN   NaN   NaN   NaN   NaN   NaN
110 Plicatoscyllium derameei             NaN   NaN   NaN   NaN   NaN   NaN
111 Plicatoscyllium gharbii              NaN   NaN   NaN   NaN   NaN   NaN
112 Plicatoscyllium globidens            NaN   NaN   NaN   NaN   NaN   NaN
113 Plicatoscyllium lehneri              NaN   NaN   NaN   NaN   NaN   NaN
114 Plicatoscyllium minutum              NaN   NaN   NaN   NaN   NaN   NaN
115 Plicatoscyllium youssoufiaense       NaN   NaN   NaN   NaN   NaN   NaN
116 Protoginglymostoma ypresiensis       NaN   NaN   NaN   NaN   NaN   NaN
117 Pseudoginglymostoma erguitaense      NaN   NaN   NaN   NaN   NaN   NaN
118 Pseudoginglymostoma idiri            NaN   NaN   NaN   NaN   NaN   NaN
119 Pseudospinax heterodon               NaN   NaN   NaN   NaN   NaN   NaN
120 Pseudospinax pusillus                NaN   NaN   NaN   NaN   NaN   NaN
121 Restesia americana                   NaN   NaN   NaN   NaN   NaN   NaN
122 Restesia nordquistae                 NaN   NaN   NaN   NaN   NaN   NaN
123 Rhincodon ferriolensis               NaN   NaN   NaN   NaN   NaN   NaN
124 Squatiscyllium casieri               NaN   NaN   NaN   NaN   NaN   NaN
125 Squatiscyllium nigeriensis           NaN   NaN   NaN   NaN   NaN   NaN
126 Stegostoma tethysiensis              NaN   NaN   NaN   NaN   NaN   NaN
    178.5 177.5 176.5 ⋯ 8.5 7.5 6.5 5.5 4.5 3.5 2.5 1.5 0.5 0
3   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
4   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
5   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
6   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
7     0     0     0   ⋯ 0   0   0   0   0   0   0   0   0   0
8   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
9   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
10  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
11  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
12  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
13  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
14  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
15  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
16  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
17  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
18  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
19  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
20  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
21  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
22  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
23  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
24  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
25  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
26  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
27  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
28  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
29  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
30  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
31  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
32  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
⋮   ⋮     ⋮     ⋮     ⋱ ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮
97  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
98  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
99  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
100 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
101 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
102 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
103 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
104 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
105 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
106 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
107 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
108 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
109 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
110 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
111 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
112 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
113 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
114 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
115 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
116 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
117 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
118 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
119 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
120 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
121 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
122 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
123 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
124 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
125 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
126 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0

In [43]:
temp_phy$V1 <- gsub("_", " ", temp_phy$V1)

In [46]:
temp_tab

    scientificName                       184.5 183.5 182.5 181.5 180.5 179.5
3   Adnetoscyllium angloparisensis       NaN   NaN   NaN   NaN   NaN   NaN
4   Almascyllium cheikheliasi            NaN   NaN   NaN   NaN   NaN   NaN
5   Annea altucuspis                     NaN   NaN   NaN   NaN   NaN   NaN
6   Annea carinata                       NaN   NaN   NaN   NaN   NaN   NaN
7   Annea maubeugei                      NaN   NaN     2     0     0     2
8   Annea myriacuspis                    NaN   NaN   NaN   NaN   NaN   NaN
9   Brachaelurid (gen. nov.) roklumensis NaN   NaN   NaN   NaN   NaN   NaN
10  Cantioscyllium alhaulfi              NaN   NaN   NaN   NaN   NaN   NaN
11  Cantioscyllium bighornensis          NaN   NaN   NaN   NaN   NaN   NaN
12  Cantioscyllium brachyplicatum        NaN   NaN   NaN   NaN   NaN   NaN
13  Cantioscyllium clementsi             NaN   NaN   NaN   NaN   NaN   NaN
14  Cantioscyllium decipiens             NaN   NaN   NaN   NaN   NaN   NaN
15  Cantioscyllium estesi                NaN   NaN   NaN   NaN   NaN   NaN
16  Cantioscyllium hashimiaensis         NaN   NaN   NaN   NaN   NaN   NaN
17  Cantioscyllium lobatum               NaN   NaN   NaN   NaN   NaN   NaN
18  Cantioscyllium markaguntensis        NaN   NaN   NaN   NaN   NaN   NaN
19  Cantioscyllium meyeri                NaN   NaN   NaN   NaN   NaN   NaN
20  Cantioscyllium nessovi               NaN   NaN   NaN   NaN   NaN   NaN
21  Cederstroemia havreensis             NaN   NaN   NaN   NaN   NaN   NaN
22  Cederstroemia nilsi                  NaN   NaN   NaN   NaN   NaN   NaN
23  Cederstroemia siverssoni             NaN   NaN   NaN   NaN   NaN   NaN
24  Cederstroemia triangulata            NaN   NaN   NaN   NaN   NaN   NaN
25  Cederstroemia ziaensis               NaN   NaN   NaN   NaN   NaN   NaN
26  Chiloscyllium broennimanni           NaN   NaN   NaN   NaN   NaN   NaN
27  Chiloscyllium frequens               NaN   NaN   NaN   NaN   NaN   NaN
28  Chiloscyllium gaemersi               NaN   NaN   NaN   NaN   NaN   NaN
29  Chiloscyllium grandis                NaN   NaN   NaN   NaN   NaN   NaN
30  Chiloscyllium greeni                 NaN   NaN   NaN   NaN   NaN   NaN
31  Chiloscyllium humboldti              NaN   NaN   NaN   NaN   NaN   NaN
32  Chiloscyllium meraense               NaN   NaN   NaN   NaN   NaN   NaN
⋮   ⋮                                    ⋮     ⋮     ⋮     ⋮     ⋮     ⋮
97  Palaeorhincodon daouii               NaN   NaN   NaN   NaN   NaN   NaN
98  Palaeorhincodon dartevellei          NaN   NaN   NaN   NaN   NaN   NaN
99  Palaeorhincodon wardi                NaN   NaN   NaN   NaN   NaN   NaN
100 Paraginglymostoma bloti              NaN   NaN   NaN   NaN   NaN   NaN
101 Parahemiscyllium underwoodwardi      NaN   NaN   NaN   NaN   NaN   NaN
102 Pararhincodon crochardi              NaN   NaN   NaN   NaN   NaN   NaN
103 Pararhincodon germaini               NaN   NaN   NaN   NaN   NaN   NaN
104 Pararhincodon groessensi             NaN   NaN   NaN   NaN   NaN   NaN
105 Pararhincodon lehmani                NaN   NaN   NaN   NaN   NaN   NaN
106 Pararhincodon ornatus                NaN   NaN   NaN   NaN   NaN   NaN
107 Pararhincodon ypresiensis            NaN   NaN   NaN   NaN   NaN   NaN
108 Phorcynis catulina                   NaN   NaN   NaN   NaN   NaN   NaN
109 Plicatoscyllium antiquum             NaN   NaN   NaN   NaN   NaN   NaN
110 Plicatoscyllium derameei             NaN   NaN   NaN   NaN   NaN   NaN
111 Plicatoscyllium gharbii              NaN   NaN   NaN   NaN   NaN   NaN
112 Plicatoscyllium globidens            NaN   NaN   NaN   NaN   NaN   NaN
113 Plicatoscyllium lehneri              NaN   NaN   NaN   NaN   NaN   NaN
114 Plicatoscyllium minutum              NaN   NaN   NaN   NaN   NaN   NaN
115 Plicatoscyllium youssoufiaense       NaN   NaN   NaN   NaN   NaN   NaN
116 Protoginglymostoma ypresiensis       NaN   NaN   NaN   NaN   NaN   NaN
117 Pseudoginglymostoma erguitaense      NaN   NaN   NaN   NaN   NaN   NaN
118 Pseudoginglymostoma idiri            NaN   NaN   NaN   NaN   NaN   NaN
119 Pseudospinax heterodon               NaN   NaN   NaN   NaN   NaN   NaN
120 Pseudospinax pusillus                NaN   NaN   NaN   NaN   NaN   NaN
121 Restesia americana                   NaN   NaN   NaN   NaN   NaN   NaN
122 Restesia nordquistae                 NaN   NaN   NaN   NaN   NaN   NaN
123 Rhincodon ferriolensis               NaN   NaN   NaN   NaN   NaN   NaN
124 Squatiscyllium casieri               NaN   NaN   NaN   NaN   NaN   NaN
125 Squatiscyllium nigeriensis           NaN   NaN   NaN   NaN   NaN   NaN
126 Stegostoma tethysiensis              NaN   NaN   NaN   NaN   NaN   NaN
    178.5 177.5 176.5 ⋯ 8.5 7.5 6.5 5.5 4.5 3.5 2.5 1.5 0.5 0
3   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
4   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
5   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
6   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
7     0     0     0   ⋯ 0   0   0   0   0   0   0   0   0   0
8   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
9   NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
10  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
11  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
12  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
13  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
14  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
15  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
16  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
17  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
18  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
19  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
20  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
21  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
22  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
23  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
24  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
25  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
26  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
27  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
28  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
29  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
30  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
31  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
32  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
⋮   ⋮     ⋮     ⋮     ⋱ ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮   ⋮
97  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
98  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
99  NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
100 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
101 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
102 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
103 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
104 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
105 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
106 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
107 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
108 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
109 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
110 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
111 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
112 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
113 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
114 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
115 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
116 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
117 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
118 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
119 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
120 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
121 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
122 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
123 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
124 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
125 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0
126 NaN   NaN   NaN   ⋯ 0   0   0   0   0   0   0   0   0   0

In [52]:
temp_phy[,1] %in% temp_tab[,1]

 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[37] FALSE FALSE

In [44]:
temp_phy

   V1                                V2
1  Brachaelurus colcloughi           6.724713
2  Brachaelurus waddi                6.724713
3  Chiloscyllium arabicum            3.626028
4  Chiloscyllium burmensis           3.626028
5  Chiloscyllium griseum             0.8858404
6  Chiloscyllium hasseltii           0.8858404
7  Chiloscyllium indicum             6.723463
8  Chiloscyllium plagiosum           6.723463
9  Chiloscyllium punctatum           6.724721
10 Cirrhoscyllium formosanum         6.724728
11 Eucrossorhinus dasypogon          6.721384
12 Ginglymostoma cirratum            4.27678
13 Ginglymostoma unami               4.27678
14 Hemiscyllium galei                5.376739
15 Hemiscyllium hallstromi           4.231966
16 Hemiscyllium halmahera            5.683715
17 Hemiscyllium henryi               5.376739
18 Hemiscyllium michaeli             3.544089
19 Hemiscyllium ocellatum            5.840748
20 Hemiscyllium strahani             6.687707
21 Hemiscyllium trispeculare         3.544089
22 Nebrius ferrugineus               6.724725
23 Orectolobus floridus              4.563025
24 Orectolobus halei                 3.88447
25 Orectolobus hutchinsi             5.817138
26 Orectolobus japonicus             1.384451
27 Orectolobus leptolineatus         1.384451
28 Orectolobus maculatus             2.067684
29 Orectolobus ornatus               6.602671
30 Orectolobus parvimaculatus        5.2138
31 Orectolobus reticulatus           5.780924
32 Orectolobus wardi                 5.780924
33 Parascyllium collare              1.466971
34 Parascyllium ferrugineum          1.466971
35 Pseudoginglymostoma brevicaudatum 6.724728
36 Rhincodon typus                   6.724728
37 Stegostoma fasciatum              6.724728
38 Sutorectus tentaculatus           4.563025

## Combining data (DES)

In [49]:
temp_tab <- read.table("../DES/Analysis_ML/sp_1/sp_1_DES_20.txt", sep ="\t")
colnames(temp_tab) <- as.character(temp_tab[1,])
temp_tab <- temp_tab[-1, ]

In [50]:
phy$tip.label

 [1] "Parascyllium_collare"              "Parascyllium_ferrugineum"
 [3] "Cirrhoscyllium_formosanum"         "Hemiscyllium_ocellatum"
 [5] "Hemiscyllium_strahani"             "Hemiscyllium_trispeculare"
 [7] "Hemiscyllium_michaeli"             "Hemiscyllium_hallstromi"
 [9] "Hemiscyllium_galei"                "Hemiscyllium_henryi"
[11] "Hemiscyllium_halmahera"            "Chiloscyllium_griseum"
[13] "Chiloscyllium_hasseltii"           "Chiloscyllium_arabicum"
[15] "Chiloscyllium_burmensis"           "Chiloscyllium_plagiosum"
[17] "Chiloscyllium_indicum"             "Chiloscyllium_punctatum"
[19] "Stegostoma_fasciatum"              "Pseudoginglymostoma_brevicaudatum"
[21] "Rhincodon_typus"                   "Ginglymostoma_cirratum"
[23] "Ginglymostoma_unami"               "Nebrius_ferrugineus"
[25] "Eucrossorhinus_dasypogon"          "Orectolobus_floridus"
[27] "Sutorectus_tentaculatus"           "Orectolobus_halei"
[29] "Orectolobus_maculatus"             "Orectolobus_japonicus"
[31] "Orectolobus_leptolineatus"         "Orectolobus_parvimaculatus"
[33] "Orectolobus_hutchinsi"             "Orectolobus_ornatus"
[35] "Orectolobus_wardi"                 "Orectolobus_reticulatus"
[37] "Brachaelurus_waddi"                "Brachaelurus_colcloughi"

In [51]:
temp_tab[3,4]

[1] NaN

In [33]:
phy <- tree_list[[1]]